# Generated by Django 4.1 on 2023-08-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("basicapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofileinfo",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profile_pics"),
        ),
    ]
